esphome:
  min_version: 2025.2.0
  name: esp32-louder
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
  # use priority -100 so gpio and i2c dac is setup before volume is set
    priority: -100
    then:
    # Set volume to 5% just to be safe...
    - media_player.volume_set:
        id: louder_mediaplayer
        volume: 5%

esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  flash_size: 16MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB: "y"

      CONFIG_ESP32_S3_BOX_BOARD: "y"

      CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST: "y"
      CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY: "y"

      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y"
      CONFIG_MBEDTLS_SSL_PROTO_TLS1_3: "y"  # TLS1.3 support isn't enabled by default in IDF 5.1.5

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  id: this_api
  encryption:
    key: "w520PFA3Ik65hxHdBkVM/Q5wR/LIngfOFfX0QgQtduM="

ota:
  - platform: esphome
    password: "35925d04e9ba07c835429bb2c040be8e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
   static_ip: 192.168.2.65
   gateway: 192.168.2.1
   subnet: 255.255.255.0

globals:
  - id: current_volume
    type: float
  - id: eq_gain_refreshed
    type: bool
    initial_value: "false"

psram:
  mode: octal
  speed: 80MHz

external_components:
  #- source:
  #    type: local
  #    path: components
  - source: github://mrtoy-me/esphome-components-test@dev
    components: [ tas5805m ]
    refresh: 0s

i2c:
  sda: GPIO8
  scl: GPIO9
  frequency: 400kHz
  scan: True

audio_dac:
  - platform: tas5805m
    id: tas5805m_dac
    enable_pin: GPIO17
    analog_gain: -13.5db

i2s_audio:
  i2s_lrclk_pin: GPIO15
  i2s_bclk_pin: GPIO14

speaker:
  - platform: i2s_audio
    id: speaker_id
    dac_type: external
    i2s_dout_pin: GPIO16
    audio_dac: tas5805m_dac
    channel: stereo
    sample_rate: 48000
    timeout: never

  - platform: mixer
    id: mixer_speaker_id
    task_stack_in_psram: true
    output_speaker: speaker_id
    source_speakers:
      - id: announcement_spk_mixer_input
        timeout: never
      - id: media_spk_mixer_input
        timeout: never

  - platform: resampler
    id: media_spk_resampling_input
    task_stack_in_psram: true
    output_speaker: media_spk_mixer_input

  - platform: resampler
    id: announcement_spk_resampling_input
    task_stack_in_psram: true
    output_speaker: announcement_spk_mixer_input

media_player:
  - platform: speaker
    name: Louder Mediaplayer
    id: louder_mediaplayer
    task_stack_in_psram: true
    volume_increment: 0.1%
    volume_min: 45%
    volume_max: 80%
    media_pipeline:
      speaker: media_spk_resampling_input
      num_channels: 2
    announcement_pipeline:
       speaker: announcement_spk_resampling_input
       num_channels: 1

    on_play:
      - if:
          condition:
            switch.is_off: enable_louder
          then:
            switch.turn_on: enable_louder
      - wait_until:
                media_player.is_playing:
      - delay: 0.5s
      - if:
          condition:
            and:
              - switch.is_on: enable_eq_control
              - lambda: return (!id(eq_gain_refreshed));
          then:
            - lambda: |-
                id(tas5805m_dac).refresh_eq_gains();
                id(eq_gain_refreshed) = true;

    on_announcement:
      - if:
          condition:
            switch.is_off: enable_louder
          then:
            switch.turn_on: enable_louder

      - lambda: id(current_volume) = id(tas5805m_dac).volume();
      - mixer_speaker.apply_ducking:
            id: media_spk_mixer_input
            decibel_reduction: 40
            duration: 0.25s
      - wait_until:
            media_player.is_announcing:
      - delay: 0.75s
      - if:
          condition:
            and:
              - switch.is_on: enable_eq_control
              - lambda: return (!id(eq_gain_refreshed));
          then:
            - lambda: |-
                id(tas5805m_dac).refresh_eq_gains();
                id(eq_gain_refreshed) = true;
      - lambda: id(tas5805m_dac).set_volume(id(announce_volume).state / 100);
      - wait_until:
          not:
            media_player.is_announcing:
      - mixer_speaker.apply_ducking:
            id: media_spk_mixer_input
            decibel_reduction: 0
            duration: 2.0s
      - lambda: id(tas5805m_dac).set_volume(id(current_volume));

number:
  - platform: template
    name: Announce Volume
    id: announce_volume
    icon: mdi:volume-source
    unit_of_measurement: "%"
    min_value: 0
    max_value: 100
    step: 1
    restore_value: true
    initial_value: 50
    optimistic: true

  - platform: template
    name: Gain 20 Hz
    id: eq_band_0_gain
    icon: mdi:volume-source
    unit_of_measurement: "dB"
    min_value: -15
    max_value: 15
    step: 1
    restore_value: true
    initial_value: 0
    optimistic: true
    on_value:
      lambda:
        id(tas5805m_dac).set_eq_gain(0, id(eq_band_0_gain).state);

  - platform: template
    name: Gain 31.5 Hz
    id: eq_band_1_gain
    icon: mdi:volume-source
    unit_of_measurement: "dB"
    min_value: -15
    max_value: 15
    step: 1
    restore_value: true
    initial_value: 0
    optimistic: true
    on_value:
      lambda:
        id(tas5805m_dac).set_eq_gain(1, id(eq_band_1_gain).state);

  - platform: template
    name: Gain 50 Hz
    id: eq_band_2_gain
    icon: mdi:volume-source
    unit_of_measurement: "dB"
    min_value: -15
    max_value: 15
    step: 0.5
    restore_value: true
    initial_value: 0
    optimistic: true
    on_value:
      lambda: id(tas5805m_dac).set_eq_gain(2, id(eq_band_2_gain).state);

  - platform: template
    name: Gain 80 Hz
    id: eq_band_3_gain
    icon: mdi:volume-source
    unit_of_measurement: "dB"
    min_value: -15
    max_value: 15
    step: 1
    restore_value: true
    initial_value: 0
    optimistic: true
    on_value:
      lambda: id(tas5805m_dac).set_eq_gain(3, id(eq_band_3_gain).state);

  - platform: template
    name: Gain 125 Hz
    id: eq_band_4_gain
    icon: mdi:volume-source
    unit_of_measurement: "dB"
    min_value: -15
    max_value: 15
    step: 1
    restore_value: true
    initial_value: 0
    optimistic: true
    on_value:
      lambda: id(tas5805m_dac).set_eq_gain(4, id(eq_band_4_gain).state);

  - platform: template
    name: Gain 200 Hz
    id: eq_band_5_gain
    icon: mdi:volume-source
    unit_of_measurement: "dB"
    min_value: -15
    max_value: 15
    step: 1
    restore_value: true
    initial_value: 0
    optimistic: true
    on_value:
      lambda: id(tas5805m_dac).set_eq_gain(5, id(eq_band_5_gain).state);

  - platform: template
    name: Gain 315 Hz
    id: eq_band_6_gain
    icon: mdi:volume-source
    unit_of_measurement: "dB"
    min_value: -15
    max_value: 15
    step: 1
    restore_value: true
    initial_value: 0
    optimistic: true
    on_value:
      lambda: id(tas5805m_dac).set_eq_gain(6, id(eq_band_6_gain).state);

  - platform: template
    name: Gain 500 Hz
    id: eq_band_7_gain
    icon: mdi:volume-source
    unit_of_measurement: "dB"
    min_value: -15
    max_value: 15
    step: 1
    restore_value: true
    initial_value: 0
    optimistic: true
    on_value:
      lambda: id(tas5805m_dac).set_eq_gain(7, id(eq_band_7_gain).state);

  - platform: template
    name: Gain 800 Hz
    id: eq_band_8_gain
    icon: mdi:volume-source
    unit_of_measurement: "dB"
    min_value: -15
    max_value: 15
    step: 1
    restore_value: true
    initial_value: 0
    optimistic: true
    on_value:
      lambda: id(tas5805m_dac).set_eq_gain(8, id(eq_band_8_gain).state);

  - platform: template
    name: Gain 1250 Hz
    id: eq_band_9_gain
    icon: mdi:volume-source
    unit_of_measurement: "dB"
    min_value: -15
    max_value: 15
    step: 1
    restore_value: true
    initial_value: 0
    optimistic: true
    on_value:
      lambda: id(tas5805m_dac).set_eq_gain(9, id(eq_band_9_gain).state);

  - platform: template
    name: Gain 2000 Hz
    id: eq_band_10_gain
    icon: mdi:volume-source
    unit_of_measurement: "dB"
    min_value: -15
    max_value: 15
    step: 1
    restore_value: true
    initial_value: 0
    optimistic: true
    on_value:
      lambda: id(tas5805m_dac).set_eq_gain(10, id(eq_band_10_gain).state);

  - platform: template
    name: Gain 3150 Hz
    id: eq_band_11_gain
    icon: mdi:volume-source
    unit_of_measurement: "dB"
    min_value: -15
    max_value: 15
    step: 1
    restore_value: true
    initial_value: 0
    optimistic: true
    on_value:
      lambda: id(tas5805m_dac).set_eq_gain(11, id(eq_band_11_gain).state);

  - platform: template
    name: Gain 5000 Hz
    id: eq_band_12_gain
    icon: mdi:volume-source
    unit_of_measurement: "dB"
    min_value: -15
    max_value: 15
    step: 1
    restore_value: true
    initial_value: 0
    optimistic: true
    on_value:
      lambda: id(tas5805m_dac).set_eq_gain(12, id(eq_band_12_gain).state);

  - platform: template
    name: Gain 8000 Hz
    id: eq_band_13_gain
    icon: mdi:volume-source
    unit_of_measurement: "dB"
    min_value: -15
    max_value: 15
    step: 1
    restore_value: true
    initial_value: 0
    optimistic: true
    on_value:
      lambda: id(tas5805m_dac).set_eq_gain(13, id(eq_band_13_gain).state);

  - platform: template
    name: Gain 16000 Hz
    id: eq_band_14_gain
    icon: mdi:volume-source
    unit_of_measurement: "dB"
    min_value: -15
    max_value: 15
    step: 1
    restore_value: true
    initial_value: 0
    optimistic: true
    on_value:
      lambda: id(tas5805m_dac).set_eq_gain(14, id(eq_band_14_gain).state);

switch:
  - platform: template
    name: Enable Louder
    id: enable_louder
    optimistic: true
    restore_mode: ALWAYS_ON
    turn_on_action:
      lambda: id(tas5805m_dac).set_deep_sleep_off();
    turn_off_action:
      lambda: id(tas5805m_dac).set_deep_sleep_on();

  - platform: template
    name: Enable EQ Control
    id: enable_eq_control
    optimistic: true
    restore_mode: ALWAYS_OFF
    turn_on_action:
      - lambda: id(tas5805m_dac).set_eq_on();
      - if:
          condition:
            and:
              - media_player.is_playing:
              - lambda: return (!id(eq_gain_refreshed));
          then:
            - lambda: |-
                id(tas5805m_dac).refresh_eq_gains();
                id(eq_gain_refreshed) = true;

    turn_off_action:
      - lambda: id(tas5805m_dac).set_eq_off();

interval:
  - interval: 30s
    then:
      - if:
          condition:
            - switch.is_on: enable_louder
            - for:
                time: 120s
                condition:
                  or:
                    - media_player.is_idle: louder_mediaplayer
                    - media_player.is_paused: louder_mediaplayer
          then:
            - switch.turn_off: enable_louder